name: Bug Report
description: File a structured bug report.
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the project!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly
      placeholder: The application crashes when...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we replicate the issue?
      placeholder: 1. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
